
library(tidyverse)
library(igraph)
library(COREnets)

# paper: https://journals.sagepub.com/doi/figure/10.1177/1477370812447738?

# read in file extensions ======================================================
files <- list.files(path="datasets/London Gang/",
                    pattern = "\\.csv$", 
                    full.names = TRUE
                    )

# read adjacency matrix ========================================================
edges <- files %>%
  purrr::discard(stringr::str_detect, pattern = "_ATTR.csv") %>%
  read_csv() %>%
  COREnets::to_matrix() %>%
  graph_from_adjacency_matrix(weighted = TRUE, mode = "undirected") %>%
  get.data.frame("edges")

# read attribute table =========================================================
nodes <- files %>%
  purrr::keep(stringr::str_detect, pattern = "_ATTR.csv") %>%
  read_csv() %>%
  as_tibble() %>%
  rename(name = X1)

# recode attribute table =======================================================
nodes %>%
  mutate(birthplace = case_when(Birthplace == 1 ~ "West Africa",
                                Birthplace == 2 ~ "Caribbean",
                                Birthplace == 3 ~ "United Kingdom",
                                Birthplace == 4 ~ "East Africa"))
# Note 17 June 2019 ============================================================
# Though the dataset was downloaded from UCINet's site there are issues with the
# reliability of variables. For instance, the original paper cited by the site
# makes no mention of some of the variables (e.g., music) and perhaps more 
# alarmingly the birthplace variables have been reorganized and no longer match
# those used in the paper. To air on the side of caution, we have recoded the 
# variables to match those reported in the UCINet site.

# build igraph object ==========================================================
g <- igraph::graph_from_data_frame(
  d = edges,
  directed = FALSE,
  vertices = nodes
)

# build final dataset ==========================================================
.network <- list(
  metadata = list(
    is_directed  = igraph::is_directed(g),
    is_weighted  = igraph::is_weighted(g),
    is_multiplex = igraph::any_multiple(g),
    node_type    = "people",
    is_two_mode  = igraph::is_bipartite(g),
    is_dynamic   = FALSE,
    are_nodes_spatial = inherits(igraph::as_data_frame(g,
                                                       what = "vertices"), "sf"),
    are_edges_spatial =  inherits(igraph::as_data_frame(g,
                                                        what = "edges"), "sf")
  ),
  node_table = as_tibble(igraph::as_data_frame(g, what = "vertices")),
  edge_table = as_tibble(igraph::as_data_frame(g, what = "edges"))
)

.introduction <- "This dataset is on co-offending individuals in a London-based
inner-city street gang from 2005 to 2009. Data comes from anonymized police
arrests and convition data for confirmed members of the gang."

.abstract <- "Despite acknowledgment of ‘hybrid’ street gangs in the literature,
there is little systematic research into ethnic heterogeneity within gangs.
This dataset was generated by researchers aiming at moving beyond the broad
categorization of the Black street gang. For this purpose, they examine an
all-Black Londonbased gang in detail, using fieldwork and police arrest data, 
and investigate the role of ethnic heterogeneity for the workings of the gang.
Findings suggest that ethnic heterogeneity within this gang is crucial for its 
criminal operation. Although there is no evidence for ethnicity-related 
specialization of crime, the structural co-offending pattern of the gang’s
activities is dominated by ethnicity."

.bibtex <- c(
  "@Article{londongang_2012,
  title   = {Ethnic Heterogeneity in the Activity and Structure of a Black Street Gang.}, 
  volume  = {9},
  issue   = {3},
  journal = {European Journal of Criminology.}, 
  author  = {Grund, T. and Densley, J.}, 
  year    = {2012},
  pages   = {388-406},
  }"
)

london_gang <- list(
  metadata = list(
    title       = "London Gang",
    name        = "london_gang",
    category    = "criminal",
    tags        = c("street gangs", "crime", "homophily", "heterogeneity",
                    "ethnicity"),
    description = .introduction,
    abstract    = .abstract
  ),
  bibtex = .bibtex,
  network = .network
)

usethis::use_data(london_gang, overwrite = TRUE)
